version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/nestjs_db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - nestjs-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: nestjs_db
    ports:
      - "27017:27017"
    networks:
      - nestjs-network
    volumes:
      - mongodb-data:/data/db

networks:
  nestjs-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
