version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    depends_on:
      - mongodb
    volumes:
      - .:/app  # Mount the current directory to the /app directory in the container (live-reloading)
      - /app/node_modules  # Ensure node_modules is not overwritten by the local volume
    networks:
      - nestjs-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: nestjs_db
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - nestjs-network
    volumes:
      - mongodb-data:/data/db

networks:
  nestjs-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
